name: Create Release on Main Push

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "latest"

      - name: Build
        run: npm i && npm run build

      - name: Create ZIP file
        run: |
          cd dist && zip -r linkedin-cv-scorer.zip *

      - name: Configure Git
        run: |
          git config --global user.email "geryit@gmail.com"
          git config --global user.name "Goksel Eryigit"

      - name: Tag the repository
        id: tag
        run: |
          # See https://docs.github.com/en/get-started/using-git/dealing-with-special-characters-in-branch-and-tag-names
          TAG=v$(date -Iseconds | sed 's/[T:\+]/-/g')
          echo "$TAG"
          echo "tag=$TAG" >> $GITHUB_OUTPUT
          git tag -a $TAG -m "Published version $TAG" ${GITHUB_SHA}
          git push origin $TAG

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: linkedin-cv-scorer.zip
          tag_name: ${{ steps.tag.outputs.tag }}
