name: Create Release on Main Push

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "latest"

      - name: Build
        run: npm i && npm run build

      - name: Create ZIP file
        run: |
          cd dist && zip -r linkedin-cv-scorer.zip *

      - name: Bump version and push tag
        id: bump
        uses: anothrNick/github-tag-action@v1 # Don't use @master or @v1 unless you're happy to test the latest version
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # if you don't want to set write permissions use a PAT token
          WITH_V: false

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: linkedin-cv-scorer.zip
          tag_name: ${{ steps.bump.outputs.new_tag }}
